name:  Weather Map Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

            #      - name: Scan Project
            #        run: ./gradlew sonarqube

      - name: Build Project
        run: ./gradlew assembleDebug
